// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/logservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLevel      string                 `protobuf:"bytes,1,opt,name=min_level,json=minLevel,proto3" json:"min_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_logservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logservice_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetMinLevel() string {
	if x != nil {
		return x.MinLevel
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_logservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_logservice_proto_rawDescGZIP(), []int{1}
}

func (x *LogLine) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

var File_proto_logservice_proto protoreflect.FileDescriptor

const file_proto_logservice_proto_rawDesc = "" +
	"\n" +
	"\x16proto/logservice.proto\x12\x05proto\")\n" +
	"\n" +
	"LogRequest\x12\x1b\n" +
	"\tmin_level\x18\x01 \x01(\tR\bminLevel\"z\n" +
	"\aLogLine\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson2?\n" +
	"\n" +
	"LogService\x121\n" +
	"\n" +
	"StreamLogs\x12\x11.proto.LogRequest\x1a\x0e.proto.LogLine0\x01B\x11Z\x0farchangel/protob\x06proto3"

var (
	file_proto_logservice_proto_rawDescOnce sync.Once
	file_proto_logservice_proto_rawDescData []byte
)

func file_proto_logservice_proto_rawDescGZIP() []byte {
	file_proto_logservice_proto_rawDescOnce.Do(func() {
		file_proto_logservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logservice_proto_rawDesc), len(file_proto_logservice_proto_rawDesc)))
	})
	return file_proto_logservice_proto_rawDescData
}

var file_proto_logservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logservice_proto_goTypes = []any{
	(*LogRequest)(nil), // 0: proto.LogRequest
	(*LogLine)(nil),    // 1: proto.LogLine
}
var file_proto_logservice_proto_depIdxs = []int32{
	0, // 0: proto.LogService.StreamLogs:input_type -> proto.LogRequest
	1, // 1: proto.LogService.StreamLogs:output_type -> proto.LogLine
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_logservice_proto_init() }
func file_proto_logservice_proto_init() {
	if File_proto_logservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logservice_proto_rawDesc), len(file_proto_logservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logservice_proto_goTypes,
		DependencyIndexes: file_proto_logservice_proto_depIdxs,
		MessageInfos:      file_proto_logservice_proto_msgTypes,
	}.Build()
	File_proto_logservice_proto = out.File
	file_proto_logservice_proto_goTypes = nil
	file_proto_logservice_proto_depIdxs = nil
}
