#!/usr/bin/env bash
# Apply an audit profile: export vars + sync Hermes config.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUDIT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=lib/audit_common.sh
source "$SCRIPT_DIR/lib/audit_common.sh"

usage() {
  echo "Usage: $(basename "$0") <profile> [--no-hermes]"
  echo ""
  echo "Profiles:"
  for f in "$AUDIT_ROOT"/profiles/*.conf; do
    [[ -f "$f" ]] && echo "  $(basename "$f" .conf)"
  done
}

if [[ $# -lt 1 ]]; then
  usage >&2
  exit 1
fi

PROFILE="$1"
NO_HERMES=0
shift
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-hermes) NO_HERMES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

export AUDIT_ROOT
load_audit_profile "$PROFILE"

# Optional GGUF preflight for llama profiles
if [[ -n "${MAIN_GGUF_CHECK:-}" ]]; then
  if [[ ! -f "$MAIN_GGUF_CHECK" ]]; then
    if [[ -n "${MAIN_GGUF_ALT:-}" && -f "$MAIN_GGUF_ALT" ]]; then
      export MAIN_GGUF="$MAIN_GGUF_ALT"
      echo "NOTE: using alternate GGUF: $MAIN_GGUF_ALT"
    else
      echo "WARNING: GGUF not found: $MAIN_GGUF_CHECK" >&2
      [[ -n "${MAIN_GGUF_ALT:-}" ]] && echo "         also missing: $MAIN_GGUF_ALT" >&2
      echo "         Download model before running llama-gemma-26b audits." >&2
    fi
  else
    export MAIN_GGUF="$MAIN_GGUF_CHECK"
  fi
fi

if [[ "$NO_HERMES" -eq 0 ]]; then
  hermes config set model.provider "$HERMES_PROVIDER"
  hermes config set model.default "$HERMES_MODEL"
  hermes config set model.base_url "$HERMES_BASE_URL"
  if [[ -n "${HERMES_CONTEXT_LENGTH:-}" ]]; then
    hermes config set model.context_length "$HERMES_CONTEXT_LENGTH"
    # >=64K required by Hermes Agent; server CTX (profile CTX=32768) is the hard API cap
    hermes config set auxiliary.compression.context_length "$HERMES_CONTEXT_LENGTH"
  fi
  # Bundled mode: disable tool loops (Ollama Gemma emits invalid terminal:* names)
  if [[ "${AUDIT_MODE:-agent}" == "bundled" ]]; then
    hermes config set toolsets '[]'
  else
    hermes config set toolsets '["hermes-cli"]'
    hermes config set agent.disabled_toolsets '["web"]'
    hermes config set context.engine compressor
    # 35B audits: enable compression so tool loops do not exceed llama-server CTX
    if [[ "${COMPRESSION_ENABLED:-false}" == "true" ]]; then
      hermes config set compression.enabled true
      hermes config set compression.threshold "${COMPRESSION_THRESHOLD:-0.58}"
    else
      hermes config set compression.enabled false
    fi
  fi
fi

# Write active profile into audit.conf for child scripts
{
  echo "# Auto-generated by apply_profile.sh — do not edit by hand"
  echo "AUDIT_PROFILE=\"$PROFILE\""
  echo "HERMES_PROVIDER=\"$HERMES_PROVIDER\""
  echo "HERMES_MODEL=\"$HERMES_MODEL\""
  echo "API_HEALTH_URL=\"$API_HEALTH_URL\""
  echo "HERMES_BASE_URL=\"$HERMES_BASE_URL\""
  echo "HERMES_CONTEXT_LENGTH=\"${HERMES_CONTEXT_LENGTH:-}\""
  echo "HERMES_EXTRA_ARGS=\"${HERMES_EXTRA_ARGS:--Q --max-turns 200}\""
  echo "SAVE_PARTIAL=\"${SAVE_PARTIAL:-1}\""
  echo "AUDIT_MODE=\"${AUDIT_MODE:-agent}\""
  echo "BACKEND_PORT=\"${BACKEND_PORT:-}\""
  echo "BACKEND_START_CMD=\"${BACKEND_START_CMD:-}\""
  echo "KV_CACHE=\"${KV_CACHE:-f16}\""
  echo "LLAMA_FIT=\"${LLAMA_FIT:-on}\""
  echo "NGL_DRAFT=\"${NGL_DRAFT:-}\""
  echo "DRAFT_MAX=\"${DRAFT_MAX:-}\""
  echo "DRAFT_MIN=\"${DRAFT_MIN:-}\""
} > "$AUDIT_ROOT/audit.conf.active"

echo "Profile: $PROFILE"
echo "  provider:  $HERMES_PROVIDER"
echo "  model:     $HERMES_MODEL"
echo "  base_url:  $HERMES_BASE_URL"
echo "  context:   ${HERMES_CONTEXT_LENGTH:-auto}"
echo "  health:    $API_HEALTH_URL"
[[ -n "${BACKEND_PORT:-}" ]] && echo "  port:      $BACKEND_PORT"
[[ -n "${LLAMA_UPSTREAM_ROOT:-}" ]] && echo "  stack:     upstream draft-mtp"
[[ -n "${HF_REPO:-}" ]] && echo "  HF:        $HF_REPO"
